# Copyright (c) 2014 Jeff Geerling
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Ref: https://github.com/geerlingguy/ansible-role-test-vms
#
# Vagrant configuration version https://www.vagrantup.com/docs/vagrantfile/version
Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "bento/ubuntu-20.04"
  config.ssh.insert_key = false
  config.vm.synced_folder '.',
                          '/vagrant',
                          disabled: true
  # Default disk size is 8GB, customize if needed
  # https://www.vagrantup.com/docs/disks/usage

  # Base virtualbox configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 1
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Node 1
  config.vm.define "node1" do |node|
    node.vm.hostname = "kwuxlab1"
    node.vm.network :private_network, ip: "192.168.56.2"
  end

  # Node 2
  config.vm.define "node2" do |node|
    node.vm.hostname = "kwuxlab2"
    node.vm.network :private_network, ip: "192.168.56.3"
  end

  # Node 3
  config.vm.define "node3" do |node|
    node.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    node.vm.hostname = "kwuxlab3"
    node.vm.network :private_network, ip: "192.168.56.4"
  end

  # Node 4
  config.vm.define "node4" do |node|
    node.vm.hostname = "kwuxlab4"
    node.vm.network :private_network, ip: "192.168.56.5"
  end
end
