---
roles:
  - name: geerlingguy.docker
    src: geerlingguy.docker
    version: 4.1.1
  - name: geerlingguy.git
    src: geerlingguy.git
    version: 3.0.0
  - name: geerlingguy.pip
    src: geerlingguy.pip
    version: 2.0.0
  - name: robustq.envoyproxy
    src: git@github.com:robustq/ansible-role-envoyproxy.git
    scm: git
    version: robustq
  - src: https://github.com/ansible-community/ansible-consul.git
    name: ansible-consul
    scm: git
    version: master
  - src: https://github.com/ansible-community/ansible-vault.git
    name: ansible-community.ansible-vault
    scm: git
    version: 08cd5a22d236f9f4f4d1ad874d90bbace8b88732
  - src: https://github.com/ansible-community/ansible-nomad.git
    name: ansible-community.ansible-nomad
    scm: git
    version: c8919d094ec6411e8d65b1abfa65d7a590e19eb3
